---
name: "Staging Tests"
# Staging Environment (code-staging) Test Suite

on:
  repository_dispatch:
    types: "trigger-staging-tests"

env:
  PROJ_NAME: "Blazor-SqLite-Golf-Club"

jobs:

  staging-tests:
  
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: (github.actor != 'CodeApprover')

    environment:
      staging

    steps:
    
    - name: Report SHA and workflow timestamp
      run: |
        echo "${{ github.event.client_payload.sha }}"
        date
 
