---
name: "SHA Failure"

on:
  workflow_run:
    workflows:
      - Report
      - Cache Dependencies
      - StyleCop Linter
      - Development Tests
      - Staging Tests
      - Production Tests
      - CodeQL
      - Superlinter
      - Check Lock File
      - Versioning
      - Deploy Docker
      - Deploy Git
      - SHA Success
    types:
      - failure

env:
  PROJ_NAME: "Blazor SqlLite Golf Club"

jobs:

  revert-commit:
    name: Revert Failed Commit
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    
    - name: Report SHA and timestamp
      run: |
        echo "${{ github.sha }}"
        date

    - name: Get SHA of Commit
      run: echo "SHA=$(echo '${{ github.event.client_payload.sha }}')" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0 # fetch entire history

    - name: Extract Branch Name from SHA Commit
      run: |
        branch=$(git branch -r --contains ${{ env.SHA }} | sed -n 's#^ *origin/##p' | head -n 1)
        if [[ -z "$branch" ]]; then
          echo "Failed to extract branch name for SHA: ${{ env.SHA }}"
          exit 1
        fi
        echo "BRANCH_NAME=$branch" >> $GITHUB_ENV

    - name: Revert commit
      run: |
        git revert ${{ env.SHA }}
        git push origin ${{ env.BRANCH_NAME }}

    - name: Check and Remove Lock File with Specific SHA
      run: |
        trap 'echo "Error on line $LINENO: $BASH_COMMAND"; exit 1' ERR
        declare -A branch_lock_map
        branch_lock_map["code-production"]=".production.lock"
        branch_lock_map["code-staging"]=".staging.lock"
        branch_lock_map["code-development"]=".development.lock"
        branch_lock_map["main"]=".main.lock"

        echo "##[debug] Branch is ${{ env.BRANCH_NAME }}"
        lock_file=${branch_lock_map[${{ env.BRANCH_NAME }}]}
        echo "##[debug] lock_file is $lock_file"

        # Check if the lock file contains the specific SHA
        if [[ $(cat "$lock_file") == "${{ github.event.client_payload.sha }}" ]]; then
          git config user.name "CodeApprover"
          git config user.email "pucfada@pm.me"
          echo "Removing lock file with SHA ${{ github.event.client_payload.sha }} found on branch ${{ env.BRANCH_NAME }}"
          git rm "$lock_file"
          if [ $? -eq 0 ]; then
              git commit -m "Removed lock after SHA ${{ github.event.client_payload.sha }} workflow failure [skip ci]"
              git push origin "${{ env.BRANCH_NAME }}"
          else
              echo "Error: Failed to remove lock file"
              exit 1
          fi
        else
          echo "Lock file with SHA ${{ github.event.client_payload.sha }} not found on branch ${{ env.BRANCH_NAME }}. Exiting."
          exit 1
        fi

  notify-committer:
    runs-on: ubuntu-latest
    needs: revert-commit

    steps:
    - name: Notify committer of SHA rejection and revert branch
      run: |
        COMMITTER=$(git log -1 --pretty=format:'%an')
        WORKFLOW_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        COMMENT_BODY="Hello @$COMMITTER, your recent commit ${{ github.event.workflow_run.head_sha }} "
        COMMENT_BODY+="has failed, been reverted, and any associated lock files were removed. "
        COMMENT_BODY+="Please check the [workflow run]($WORKFLOW_LINK) for details, "
        COMMENT_BODY+="address any issues and try pushing again. Thank you!"
        
        CURL_CMD="curl -X POST"
        CURL_CMD+=" -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\""
        CURL_CMD+=" -H \"Accept: application/vnd.github.v3+json\""
        CURL_CMD+=" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/comments"
        CURL_CMD+=" -d \"{\\\"body\\\":\\\"$COMMENT_BODY\\\"}\""
        eval "$CURL_CMD"

  # reset the code-dev ??? what about concurrent commits? push dev dir to main and clone main...
