---
name: "Linters"

on:
  workflow_run:
    workflows: Report
    types:
      - completed

env:
  PROJECT_PATH: "${{ github.workspace }}/$(echo ${{ github.ref }} | grep -oE '[^-]+$')/Blazor-SqlLite-DevOps/Blazor SqlLite Golf Club/"

jobs:

  #  StyleCop Linting - https://github.com/StyleCop/StyleCop
  stylecop-linting:
    name: Dev StyleCop Linting
    runs-on: ubuntu-latest
    environment:
      development
    if: startsWith(github.ref, 'refs/heads/code-development') && github.event_name == 'workflow_run'
    needs: dev-unit-tests
    steps:
      - name: StyleCop Checkout repository
        uses: actions/checkout@v3.5.3
      - name: StyleCop Setup .NET environment
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '7.0.x'
      - name: StyleCop Restore Dependencies
        run: |
          command="dotnet restore --no-cache"
          command="${command} \"${{ env.PROJECT_PATH }}"
          command="${command}Blazor SqlLite Golf Club.csproj\""
          eval "${command}"
      - name: StyleCop dotnet build
        run: |
          command="dotnet build --no-restore"
          command="${command} \"${{ env.PROJECT_PATH }}"
          command="${command}Blazor SqlLite Golf Club.csproj\""
          command="${command} /p:StyleCopEnabled=true"
          command="${command} /p:StyleCopTreatErrorsAsWarnings=false"
          command="${command} /p:StyleCopForceFullAnalysis=false"
          eval "${command}"
