name: "Development Tests"

on:
  repository_dispatch:
    types: "trigger-development-tests"

env:
  PROJ_NAME: "Blazor-SqLite-Golf-Club"

jobs:

  development-testing:

    name: Unit Tests (${{ matrix.test_framework }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: (github.actor != 'CodeApprover')

    environment:
      development

    strategy:
      matrix:
        test_framework: [Nunit, Xunit]

    steps:

    - name: Report SHA and workflow timestamp
      run: |
        echo "${{ github.event.client_payload.sha }}"
        date

    - name: Checkout SHA repository
      uses: actions/checkout@v3.5.3
      with:
        ref: ${{ github.event.client_payload.sha }}
        fetch-depth: 0 # Fetch all

    # Added cache retrieval step
    - name: Retrieve Cached dotnet Dependencies
      id: cache-dotnet-restore
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-dotnet-${{ env.BRANCH_NAME }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Install dependencies
      if: steps.cache-dotnet-restore.outputs.cache-hit != 'true' # Only if cache was not hit
      run: |
        if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
          test_type="Nunit_Player_Unit_Tests"
        else
          test_type="Xunit_Game_Unit_Tests"
        fi
        CMD="dotnet restore --no-cache"
        CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
        eval "$CMD"

    - name: Run Nunit and Xunit unit tests
      run: |
        if [ "${{ matrix.test_framework }}" == "Nunit" ]; then
          test_type="Nunit_Player_Unit_Tests"
          log_file_name="nunit-results.trx"
        else
          test_type="Xunit_Game_Unit_Tests"
          log_file_name="xunit-results.trx"
        fi
        CMD="dotnet test"
        CMD+=" --no-restore --verbosity detailed"
        CMD+=" --logger \"trx;LogFileName=${log_file_name}\""
        CMD+=" \"${{ github.workspace }}/tests/${test_type}/${test_type}.csproj\""
        eval "$CMD"

  trigger-next-workflow:

    name: Trigger Next Workflow
    runs-on: ubuntu-latest
    needs: development-testing
    timeout-minutes: 15

    steps:

    - name: Trigger Lock File Check
      run: |
        CMD="curl -X POST -H \"Authorization: Bearer ${{ secrets.AUTH }}\" "
        CMD+="-H \"Accept: application/vnd.github.v3+json\" "
        CMD+="https://api.github.com/repos/${{ github.repository }}/dispatches "
        CMD+="-d '{\"event_type\": \"trigger-check-lock-file\", "
        CMD+="\"client_payload\": {\"sha\": \"${{ github.event.client_payload.sha }}\"}}'"
        eval ${CMD}
